version: 0.0.{build}
image:
  - Ubuntu
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore src/Vlingo.Wire.sln
build:
  project: src/Vlingo.Wire.sln
  verbosity: minimal
  publish_nuget: true
before_test:
  - sudo ufw disable
test_script:
- dotnet test src/Vlingo.Wire.Tests
deploy:
- provider: NuGet
  api_key:
    secure: S7SGXqFTXTOVbVLP45Ofyf/iTsIOr9o0F/QEeQkaUMqb/PkwWjXK6+CF4WAqbfWr
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true