version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
  - macOS-Mojave
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore src/Vlingo.Wire.sln
build:
  project: src/Vlingo.Wire.sln
  verbosity: minimal
  publish_nuget: true
for:
  -
    matrix:
      only:
        - image: macOS
    before_test:
      - defaults write /Library/Preferences/com.apple.alf globalstate -int 0
      - launchctl unload /System/Library/LaunchAgents/com.apple.alf.useragent.plist
      - launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
    after_test:
      - defaults write /Library/Preferences/com.apple.alf globalstate -int 1
      - launchctl unload /System/Library/LaunchAgents/com.apple.alf.useragent.plist
      - launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
test_script:
- dotnet test src/Vlingo.Wire.Tests
deploy:
- provider: NuGet
  api_key:
    secure: S7SGXqFTXTOVbVLP45Ofyf/iTsIOr9o0F/QEeQkaUMqb/PkwWjXK6+CF4WAqbfWr
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true